version = "1.0"

[main]

name = "Configuration for listen Prometheus"

    [main.location_prometheus]
    name = "External or local Prometheus Server ?"

        [main.location_prometheus.external]
        ask = "Is your Server Promotheus on external server ?"
        type = "boolean"
    default = false
        help= " No = your Prometheus server in on the same local server, Yes = Prometheus server is external"

        [main.location_prometheus.ip_prometheus_server]
        ask = "IP(s) Server Prometheus"
        type = "tags"
        help = "Your Prometheus server IP, by default local `127.0.0.1`. If external(s) Prometheus server(s) enabled, add the Prometheus IPv4(s)"

        [main.location_prometheus.ip_yunohost_server]
        ask = "IP listen by Promotheus"
        type = "string"
        help = "by default with local Prometheus the node listen `127.0.0.1`, if external prometheus server enabled, must be replaced by the IP server = `$(curl -s https://ip.yunohost.org/)`"
