version = "1.0"

    [main.ip_prometheus]
    name = "external or local IP Prometheus Server ?"

        [main.ip_prometheus.ip_prometheus_server]
        ask = "IP Server Prometheus"
        type = "string"
        default= "127.0.0.1"
        help = "If your Prometheus server in on the same local server let default 127.0.0.1, if your Prometheus server is external with public address add after the IP a CIDR `/32` ( <IPv4_ADDRESS>/32 )"
        bind = "IP_PROMOTHEUS_SERVER:/etc/yunohost/hooks.d/post_iptable_rules/80-nodexport"

        [main.ip_prometheus.ip_yunohost_server]
        ask = "Is your Server Promotheus on the same server ?"
        type = "boolean"
        help= " yes = your Prometheus server Iin on the same local server let default 127.0.0.1, no = Prometheus server is external"
        bind = "IP_YUNOHOST_SERVER:/etc/system/systemd/node-exporter.service"