#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "node_exporter"
name = "Node Exporter"
description.en = "Node exporter for Prometheus"
description.fr = "Node exporter pour Prometheus"

version = "1.2.0~ynh1"

maintainers = []

[upstream]
license = "Apache 2.0"
website = "https://prometheus.io/docs/guides/node-exporter/"
code = "https://github.com/prometheus/node_exporter"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz"
    amd64.sha256 = "344bd4c0bbd66ff78f14486ec48b89c248139cdd485e992583ea30e89e0e5390"
    arm64.url = "https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz"
    arm64.sha256 = "b78464d8bd1b770a7f818d20c78410090f64a91b13577f1883dca1eec5aedbc9"
    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 9100
    main.exposed = "TCP"
