#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "node_exporter"
name = "Node Exporter"
description.en = "Monitor YunoHost with prometheus"
description.fr = "Surveiller YunoHost avec prometheus"

version = "1.11.1~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://prometheus.io/docs/guides/node-exporter/"
admindoc = "https://prometheus.io/docs/guides/node-exporter/"
code = "https://github.com/prometheus/node_exporter"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "12M"
ram.build = "75M"
ram.runtime = "9M"

[install]
    [install.domain]
    type = "domain"

    [install.external]
    ask.en = "Is your Server Promotheus on external server ?"
    type = "boolean"
    default = false

    [install.ip_prometheus_server]
    ask = "IP Server Prometheus"
    type = "tags"
    default = "127.0.0.1"
    help = "Your Prometheus server IP is local by default local `127.0.0.1`, if external(s) Prometheus server(s) enabled, add the Prometheus(s) IPv4(s)"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/prometheus/node_exporter/releases/download/v1.11.1/node_exporter-1.11.1.linux-amd64.tar.gz"
    amd64.sha256 = "9f5ea48e5bc7b656f8a91a32e7d7deb89f70f73dabd0d974418aca15f37d6810"
    arm64.url = "https://github.com/prometheus/node_exporter/releases/download/v1.11.1/node_exporter-1.11.1.linux-arm64.tar.gz"
    arm64.sha256 = "ba1886efbd76cb96b0087c695ea8d1b9cb6e8aa946c996d744e9ee16c8e3591a"
    armhf.url = "https://github.com/prometheus/node_exporter/releases/download/v1.11.1/node_exporter-1.11.1.linux-armv7.tar.gz"
    armhf.sha256 = "661c662e566d5c68950d63f7dfd1ec46ba28858f91aeba220c32baa1d3ad7b33"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*linux-amd64.tar.gz"
    autoupdate.asset.armhf = ".*linux-armv7.tar.gz"
    autoupdate.asset.arm64 = ".*linux-arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"
    api.url = "/metrics"
    api.allowed = "visitors"

    [resources.ports]
    # NB : The port is actually exposed via a custom iptable rule to only expose it to the prometheus IP (if set as 'external')
    main.default = 9100

