#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "node_exporter"
name = "Node Exporter"
description.en = "Monitor YunoHost with prometheus"
description.fr = "Surveiller YunoHost avec prometheus"

version = "1.9.0~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://prometheus.io/docs/guides/node-exporter/"
admindoc = "https://prometheus.io/docs/guides/node-exporter/"
code = "https://github.com/prometheus/node_exporter"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "12M"
ram.build = "75M"
ram.runtime = "9M"

[install]
    [install.domain]
    type = "domain"

    [install.ipv4_promotheus_server]
    ask.en = "Promotheus external Server IPv4 Address"
    ask.fr = "Adresse IPv4 du serveur externe Promotheus"
    type = "string"    
    help.en = "If your Promotheus server is public add a CIDR `/32` (exemple: IPv4_ADDRESS/32)"
    help.fr = "Si votre serveur Promotheus est public, ajoutez un CIDR `/32` (exemple IPv4_ADDRESS/32)"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/prometheus/node_exporter/releases/download/v1.9.0/node_exporter-1.9.0.linux-amd64.tar.gz"
    amd64.sha256 = "e7b65ea30eec77180487d518081d3dcb121b975f6d95f1866dfb9156c5b24075"
    arm64.url = "https://github.com/prometheus/node_exporter/releases/download/v1.9.0/node_exporter-1.9.0.linux-arm64.tar.gz"
    arm64.sha256 = "5314fae1efff19abf807cfc8bd7dadbd47a35565c1043c236ffb0689dc15ef4f"
    armhf.url = "https://github.com/prometheus/node_exporter/releases/download/v1.9.0/node_exporter-1.9.0.linux-armv7.tar.gz"
    armhf.sha256 = "27ff7b105fd4cfc58c2762a6387d93e62eb55473cb5111eb5feb7086c60ef05f"
    
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*linux-amd64.tar.gz"
    autoupdate.asset.armhf = ".*linux-armv7.tar.gz"
    autoupdate.asset.arm64 = ".*linux-arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"
    api.url = "/metrics"
    api.allowed = ["visitors", "admins"]

    [resources.ports]
    main.default = 9100
    main.exposed = "TCP"
