#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "node_exporter"
name = "Node Exporter"
description.en = "Monitor YunoHost with prometheus"
description.fr = "Surveiller YunoHost avec prometheus"

version = "1.9.1~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://prometheus.io/docs/guides/node-exporter/"
admindoc = "https://prometheus.io/docs/guides/node-exporter/"
code = "https://github.com/prometheus/node_exporter"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "12M"
ram.build = "75M"
ram.runtime = "9M"

[install]
    [install.domain]
    type = "domain"

    [install.ip_prometheus_server]
    ask.en = "Promotheus Server IPv4 Address"
    ask.fr = "Adresse IPv4 du serveur externe Promotheus"
    type = "string"
    default= "127.0.0.1"
    help.en = "If your Prometheus server in on the same server choose 127.0.0.1, if your Prometheus server is external with public address add after the IP a CIDR `/32` ( <IPv4_ADDRESS>/32 )"
    help.fr = "Si votre serveur Promotheus est local choisissez `127.0.0.1`, si votre serveur Prometheus est externe avec une adresse publique, ajoutez un CIDR `/32` ( <IPv4_ADDRESS>/32 )"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/prometheus/node_exporter/releases/download/v1.9.1/node_exporter-1.9.1.linux-amd64.tar.gz"
    amd64.sha256 = "becb950ee80daa8ae7331d77966d94a611af79ad0d3307380907e0ec08f5b4e8"
    arm64.url = "https://github.com/prometheus/node_exporter/releases/download/v1.9.1/node_exporter-1.9.1.linux-arm64.tar.gz"
    arm64.sha256 = "848f139986f63232ced83babe3cad1679efdbb26c694737edc1f4fbd27b96203"
    armhf.url = "https://github.com/prometheus/node_exporter/releases/download/v1.9.1/node_exporter-1.9.1.linux-armv7.tar.gz"
    armhf.sha256 = "f04c95c9c474516b06ab10e34a663992ccad4c9185596e404f02790ec23d83d9"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*linux-amd64.tar.gz"
    autoupdate.asset.armhf = ".*linux-armv7.tar.gz"
    autoupdate.asset.arm64 = ".*linux-arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"
    main.auth_header = false
    api.url = "/metrics"
    api.allowed = "visitors"

    [resources.ports]
    main.default = 9100
    main.exposed = "TCP"
