#!/bin/bash

source /usr/share/yunohost/helpers

line_port=$(iptables -xvnL --line-numbers |grep $port |cut -d' ' -f1) || true
line_port6=$(ip6tables -xvnL --line-numbers |grep $port |cut -d' ' -f1) || true

if [ "$ip_prometheus_server" == "127.0.0.1" ]; then
	ip_yunohost_server="127.0.0.1"
else
	ip_yunohost_server="$(curl -s https://ip.yunohost.org/)"
fi

# Add only promotheus server accept rules
iptables -R INPUT __LINE_PORT__ -s __IP_PROMETHEUS_SERVER__ -p tcp -m tcp --dport __PORT__ -j ACCEPT
ip6tables -R INPUT __LINE_PORT6__ -p tcp --dport __PORT__ -j DROP

yunohost firewall reload --debug