#!/bin/bash

# IMPORT GENERIC HELPERS and load common variables and helpers
source /usr/share/yunohost/helpers
source ${pwd}/../../apps/${app}/scripts/_common.sh

# Add only promotheus server accept rules
iptables -R INPUT __LINE_PORT__ -s __IP_PROMETHEUS_SERVER__ -p tcp -m tcp --dport __PORT__ -j ACCEPT
exit 0

iptables -save