#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP SYSTEM CONFIGURATION
#=================================================

# Backup the systemd service unit
ynh_backup "/etc/systemd/system/$app.service"

if [ "$ip_prometheus_server" != "127.0.0.1"  ]; then
# Backup the hook iptables
ynh_backup "/etc/yunohost/hooks.d/post_iptable_rules/80-nodexport"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
