#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

ynh_app_config_validate() {
    _ynh_app_config_validate
    if [ "${changed[external]}" == "true" ] && [ $external -eq 1 ] && [ "$ip_yunohost_server" == "127.0.0.1" ]
         ynh_die --message="You need to change the IP listen by Promotheus by the IP server = `$(curl -s https://ip.yunohost.org/)`"
    fi

    if [ "${changed[external]}" == "true" ] && [ $external -eq 1 ] && [ "$ip_prometheus_server" == "127.0.0.1" ]
    then
        ynh_die --message="You need to choose an external IP for Promotheus"
    fi

    if [ "${changed[external]}" == "true" ] && [ $external -eq 0 ] && [ ! "$ip_yunohost_server" == "127.0.0.1" ]
    then
        ynh_die --message="You need to choose `127.0.0.1` for IP for Promotheus"
    fi

    if [ "${changed[external]}" == "true" ] && [ $external -eq 0 ] && [ ! "$ip_prometheus_server" == "127.0.0.1" ]
    then
        ynh_die --message="You need to choose `127.0.0.1` to listen local Promotheus"
    fi
}

ynh_app_config_apply() {
    _ynh_app_config_apply

    if [ "${changed[external]}" == "true" ] && [ $external -eq 1 ]
    then
        ynh_app_setting_set --app="$app" --key="ip_yunohost_server" value="$(curl -s https://ip.yunohost.org/)"
        ynh_systemctl --service="node_exporter" --action=restart

        if [ ! "$ip_prometheus_server" == "127.0.0.1" ]
        then
            yunohost firewall reload --debug
        fi
    elif [ "${changed[external]}" == "true" ] && [ $external -eq 0 ]
    then
        ynh_app_setting_set --app="$app" --key="ip_yunohost_server" value="127.0.0.1"
        ynh_app_setting_set --app="$app" --key="ip_promotheus_server" value="127.0.0.1"
        ynh_systemctl --service="node_exporter" --action=restart
        yunohost firewall reload --debug
    fi

    if [ "${changed[ip_yunohost_server]}" == "true" ] && [ ! "$ip_yunohost_server" == "127.0.0.1" ]
    then
        ynh_systemctl --service="node_exporter" --action=restart
    fi

    if [ "${changed[ip_prometheus_server]}" == "true" ] && [ ! "$ip_prometheus_server" == "127.0.0.1" ]
    then
        yunohost firewall reload --debug
    fi
}

ynh_app_config_run $1


# # hook_extra_conf_dir="/etc/yunohost/hooks.d/post_iptable_rules"
# set__ip_prometheus_server() {
#     if [ "$ip_prometheus_server" == "127.0.0.1" ]; then
#        yunohost firewall reload --debug
#        ynh_print_info "Node exporter now listen local server Prometheus"
#     else
#         yunohost firewall reload --debug
#         ynh_print_info "Node exporter now listen external server Prometheus"
#     fi
#     ynh_app_setting_set --key="ip_prometheus_server" --value="$ip_prometheus_server"
# }

# set__ip_yunohost_server() {
#     if [ "$ip_yunohost_server" eq "0" ]; then
#        # value IP local to listen for service
#        ynh_app_setting_set --app="$app" --key="ip_yunohost_server" value="127.0.0.1"
#        ynh_systemctl --service="node_exporter" --action=restart
#     elif [ "$ip_yunohost_server" eq "1" ]; then
#         # value IP server external to listen for service
#         ynh_app_setting_set --app="$app" --key="ip_yunohost_server" value="$(curl -s https://ip.yunohost.org/)"
#         ynh_systemctl --service="node_exporter" --action=restart
#     fi
#      ynh_app_setting_set --key="ip_yunohost_server" --value="$ip_yunohost_server"
# }

