#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_config_remove_systemd

# Remove YunoHost hook
ynh_safe_rm "/etc/yunohost/hooks.d/post_iptable_rules/50-nodexport"

# Remove diagnosis ignore
yunohost diagnosis run ports
yunohost diagnosis unignore --filter ports port=$port

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
